language: java
os: linux
dist: bionic
arch: amd64
jdk:
#  - openjdk8
#  - openjdk11
  - openjdk-ea

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: clean
      script: ./mvnw clean
    - stage: install
      script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      script: ./mvnw test -B
    - stage: codecov
      script: bash <(curl -s https://codecov.io/bash)
    - stage: build image
      script: ./mvnw spring-boot:build-image
    - stage: pull docker hub
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push spring-business
    - stage: deploy heroku
      deploy:
        provider: heroku
        app: spring-business
        api_key: $HEROKU_AUTH_TOKEN


notifications:
  email: true