language: java
os: linux
dist: bionic
arch: amd64
jdk:
#  - openjdk8
#  - openjdk11
  - openjdk-ea

branches:
  only:
    - master

services:
  - docker

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: clean amd install
      script:
        - ./mvnw clean
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test and codecov
      script:
        - ./mvnw test -B
        - bash <(curl -s https://codecov.io/bash)
    - stage: build image and push imaga to docker hub
      script:
        - ./mvnw spring-boot:build-image
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - docker tag spring-business $DOCKER_USERNAME/spring-business:0.0.1-SNAPSHOT
        - docker push $DOCKER_USERNAME/spring-business:0.0.1-SNAPSHOT
    - stage: deploy heroku
      deploy:
        provider: heroku
        app: spring-business
        api_key: $HEROKU_AUTH_TOKEN


notifications:
  email: true